export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #fce3ec 0%, #f8f9fa 100%)' },    // Pink Blossom
  { id: 2, bgcolor: 'linear-gradient(135deg, #e0f7fa 0%, #ffffff 100%)' },    // Aqua Breeze
  { id: 3, bgcolor: 'linear-gradient(135deg, #e3fcec 0%, #f9fffc 100%)' },    // Mint Cream
  { id: 4, bgcolor: 'linear-gradient(135deg, #fff3e0 0%, #fffaf3 100%)' },    // Peach Light
  { id: 5, bgcolor: 'linear-gradient(135deg, #ede7f6 0%, #f5f3ff 100%)' },    // Lavender Fog
  { id: 6, bgcolor: 'linear-gradient(135deg, #e0f2f1 0%, #f1fafa 100%)' },    // Teal Mist
  { id: 7, bgcolor: 'linear-gradient(135deg, #fffde7 0%, #ffffff 100%)' },    // Sun Glow
  { id: 8, bgcolor: 'linear-gradient(135deg, #e8f5e9 0%, #f7fcf9 100%)' },    // Spring Meadow
  { id: 9, bgcolor: 'linear-gradient(135deg, #f3e5f5 0%, #fcf4ff 100%)' },    // Soft Purple
  { id: 10, bgcolor: 'linear-gradient(135deg, #fce4ec 0%, #fff5f8 100%)' },   // Blush Petal
];


export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no fluff.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organized.",
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Save Organize, and Revisit",
    description:
    "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off. "
  },
];
